# Generated by Django 5.2 on 2025-04-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'verbose_name': 'Pessoa Física', 'verbose_name_plural': 'Pessoas Físicas'},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={'verbose_name': 'Pessoa Jurídica', 'verbose_name_plural': 'Pessoas Jurídicas'},
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='business_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='E-mail do Empreendimento'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
    ]
